# Generated by Django 4.1 on 2022-08-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RemoveField(
            model_name="comment",
            name="published_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="published_at",
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("published", "Published"), ("draft", "Draft")],
                default="draft",
                max_length=10,
            ),
        ),
    ]
