# Generated by Django 4.1 on 2022-08-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_remove_comment_url_remove_post_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("draft", "Draft"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
    ]
