# Generated by Django 4.1 on 2022-08-25 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_alter_comment_options_remove_comment_parent_id_and_more"),
        ("mainapp", "0004_alter_post_status"),
    ]

    operations = []
