# Generated by Django 4.1 on 2022-08-29 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_merge_20220825_1938"),
        ("mainapp", "0005_merge_20220826_1125"),
    ]

    operations = []
